// Offline help for common questions. Specific model support needs manufacturer documentation.
export function hardwareHelp(raw){
  const text=String(raw).toLowerCase(),laptop=/laptop|notebook|macbook/.test(text);
  if(/overheat|too hot|running hot|fan.*loud|loud.*fan/.test(text))return 'For an overheating '+(laptop?'laptop':'PC')+':\n1. Use a hard, flat surface and keep air vents clear.\n2. Check Task Manager for an app using lots of CPU or GPU.\n3. Shut down before cleaning external vents; use the maker’s maintenance instructions.\n4. If it still shuts down or overheats, have its cooling system checked.\n\nWhat is the exact model, and does this happen at idle or while gaming? I can’t read its temperature from this page.';
  if(/(?:upgrade|add|replace|expand).*(?:ram|memory)|(?:ram|memory).*(?:upgrade|add|replace|expand)/.test(text)&&laptop)return 'Laptop RAM upgrades depend on the exact model. Some use soldered memory; others have SO-DIMM slots. Check its service manual for DDR generation, maximum capacity and slot count. Desktop DIMMs will not fit laptop SO-DIMM slots.\n\nSend the full laptop model and its current RAM. I’ll help you work out what to check before buying.';
  if(/slow|slowing|lagging|laggy/.test(text))return 'Start by finding what is busy: open Task Manager and check CPU, Memory and Disk while the slowdown happens. Close unused apps, review startup apps, free storage space and install updates from the OS or device maker. Back up important files before changing storage or reinstalling anything.\n\nIs it slow at startup, in a browser, or in a specific game? Share the model, RAM and whether it uses an SSD or hard drive.';
  if(/not charging|won.t charge|doesn.t charge|charger.*work/.test(text))return 'Check the wall socket, cable and connector, then confirm the charger is approved for your exact laptop and supplies the required power. A USB-C connector alone does not guarantee charging support. Restart and check the maker’s battery diagnostics or charging-limit setting.\n\nWhat laptop model and charger wattage do you have?';
  if(/battery/.test(text))return 'To improve laptop battery life, reduce screen brightness, use the operating system’s power-saving mode and check which apps use the most energy. Battery wear, workload and display settings all matter. A maker’s charging-limit feature can help if the laptop stays plugged in most of the time.\n\nAre you asking about short runtime, battery health, or charging?';
  if(/no display|black screen|screen.*blank|no signal/.test(text))return 'Check that the display has power and is on the correct input, then reconnect the video cable. On a desktop with a separate graphics card, the monitor usually needs to connect to that card. Try another cable or display if available.\n\nDo you see the manufacturer logo at startup, and are the PC’s fans or lights turning on?';
  if(/blue screen|bsod|crash|crashing/.test(text))return 'Note the exact error or stop code and when it appears. If this began after a driver, app or hardware change, that is a useful clue. Back up your files, install updates from official sources and check the system’s reliability or event history.\n\nSend the error text and your PC or laptop model. Avoid a reset or reinstall until we know what is failing.';
  if(/wi-fi|wifi|internet.*slow|network/.test(text))return 'First check whether another device has the same problem. If every device is affected, investigate the router or connection. If only this PC is affected, reconnect to Wi-Fi, check airplane mode and update its network driver from the device maker.\n\nDoes it fail on every network, or only your home Wi-Fi?';
  if(/ssd.*(?:fit|upgrade|compatible)|(?:upgrade|add).*(?:ssd|storage)/.test(text)&&laptop)return 'Check your laptop’s service manual for supported drive size and interface: M.2 NVMe, M.2 SATA and 2.5-inch SATA are different. Some laptops have a spare slot; others require replacing the current drive. Back up your files and recovery information before a replacement.\n\nWhat is the exact model and current drive?';
  if(/(?:16|32|64)\s*gb.*(?:ram|memory)?.*enough|(?:ram|memory).*enough|how much ram/.test(text))return 'For everyday work and many games, 16GB RAM can be a useful starting point. 32GB gives more room for multitasking and heavier creative work. Video projects, virtual machines and local AI can need more. Capacity needs depend on your actual apps, and the memory must match the system.\n\nWhat apps or games do you use, and is this for a laptop or a desktop?';
  if(/laptop.*(?:gpu|graphics).*(?:upgrade|replace)|(?:upgrade|replace).*(?:laptop.*(?:gpu|graphics))/.test(text))return 'Most laptop graphics chips are soldered in and cannot be upgraded like desktop graphics cards. External GPU support depends on the exact laptop, port and operating system. Tell me the model and the apps or games you want to improve.';
  if(/what is.*(?:laptop|pc|computer)|what.*laptop.*(?:best|good)|laptop.*desktop|desktop.*laptop/.test(text))return 'A laptop gives you portability, a built-in display and battery. A desktop generally offers more component choices and easier upgrades, but needs a monitor and peripherals. Choose based on where you work, your software and total budget.\n\nWill you carry it regularly, and what will you mainly use it for?';
  if(/(?:best|which|choose|need).*(?:laptop|notebook)/.test(text))return 'Tell me your budget and main use: study, coding, gaming, editing or 3D work. Also say whether battery life, weight or gaming performance matters most. I can then narrow the search and show product photos and retailer links.';
  return null;
}
