import {useState,useEffect,useRef} from 'react';
import {useApp} from '../hooks/useApp';
import {demoBuild} from '../data/hardware';
import {analyzeBuild} from '../utils/performanceEngine';
import {checkCompatibility} from '../utils/compatibilityEngine';
import {voiceAssistant,assistantLines} from '../services/voiceAssistant';
import {ComponentForm,ScoreDisplay} from '../components/BuildTools';
import {Heading,Action,Note,NextLink} from '../components/Primitives';
export default function Analyzer(){const{currentBuild,setCurrentBuild,go,demoRevision,setNotice}=useApp(),[result,setResult]=useState(null),[phase,setPhase]=useState(''),timers=useRef([]),output=useRef();
 useEffect(()=>{setResult(null);setPhase('');timers.current.forEach(clearTimeout);},[currentBuild,demoRevision]);useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
 const checks=checkCompatibility(currentBuild);
 function analyze(){if(!checks.compatible)return;setNotice('');timers.current.forEach(clearTimeout);setResult(null);const words=['CPU.','GPU.','MEMORY.','POWER.','BALANCE.'];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;words.forEach((word,i)=>timers.current.push(setTimeout(()=>setPhase(word),reduced?0:i*240)));timers.current.push(setTimeout(()=>{setPhase('');setResult(analyzeBuild(currentBuild));voiceAssistant.speak(assistantLines.results);requestAnimationFrame(()=>output.current?.scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'}));},reduced?0:1300));}
 return <section className="page analyzer-page"><Heading eyebrow="03 / PC ANALYZER" description="No downloads. No guesswork about your parts. Select what’s inside.">LET’S SEE<br/>WHAT YOU’VE <span className="orange-text">GOT.</span></Heading><div className="form-topline"><span className="eyebrow">YOUR CURRENT HARDWARE</span><button className="text-action" onClick={()=>setCurrentBuild({...demoBuild})}>Load demo PC ↗</button></div><ComponentForm build={currentBuild} onChange={setCurrentBuild}/>{!checks.compatible&&<div className="error-message" role="status"><strong>Resolve compatibility first.</strong> {checks.checks.filter(c=>!c.pass).map(c=>c.detail).join(' · ')} <button className="inline-button" onClick={()=>go('/compatibility')}>Review checks ↗</button></div>}<div className="form-actions"><Action onClick={analyze} disabled={Boolean(phase)||!checks.compatible} data-cursor="ANALYZE">{phase?'Analyzing…':'Analyze my PC'}</Action><Note>Analysis runs in your browser using your selected components.</Note></div>{phase&&<div className="analysis-phase" role="status">{phase}</div>}{result&&<div className="analysis-result" ref={output}><span className="eyebrow">ALL RIGHT. HERE’S THE PICTURE.</span><ScoreDisplay analysis={result}/><div className="limiter-scene"><span className="eyebrow">WHAT MIGHT HOLD YOU BACK?</span><h2>{result.limiter==='Balanced'?'NICE BALANCE.':result.limiter.toUpperCase()+'.'}</h2><p>{result.explanation}</p><Note>This is a workload-based heuristic, not a measured bottleneck percentage.</Note></div><div className="result-actions"><Action to="/upgrade">Find my next upgrade</Action><Action to="/performance" secondary>Estimate game performance</Action></div></div>}</section>;}
