import {useState} from 'react';
import {useApp} from '../hooks/useApp';
import {designBriefs,generateBuild} from '../utils/buildGenerator';
import {partsOf,money,priceOf,demoBuild} from '../data/hardware';
import {analyzeBuild} from '../utils/performanceEngine';
import {Heading,NativeSelect,Note} from '../components/Primitives';
import PCIllustration from '../components/PCIllustration';
import {checkCompatibility} from '../utils/compatibilityEngine';
export default function Compare(){const{currentBuild}=useApp(),[a,setA]=useState('current'),[b,setB]=useState('player');const options=[{value:'current',label:'My current build'},{value:'demo',label:'Demo PC'},...designBriefs.map(d=>({value:d.id,label:d.name}))];const get=id=>id==='current'?currentBuild:id==='demo'?demoBuild:generateBuild(designBriefs.find(d=>d.id===id).budget,designBriefs.find(d=>d.id===id).purpose).build;const builds=[get(a),get(b)],parts=builds.map(partsOf),scores=builds.map(analyzeBuild),valid=builds.map(x=>checkCompatibility(x).compatible);return <section className="page compare-page"><Heading eyebrow="07 / BUILD COMPARISON" description="The right winner depends on what you do.">THIS ONE.<br/><span className="orange-text">OR THAT ONE?</span></Heading><div className="comparison-head">{[a,b].map((v,i)=><div key={i} className={`comparison-half half-${i}`}><div className="compare-label"><span>BUILD {i===0?'A':'B'}</span><NativeSelect label={`Choose build ${i===0?'A':'B'}`} value={v} onChange={i===0?setA:setB} options={options}/></div><PCIllustration accent={i===0?'#ff343b':'#b01e2b'} variant={i+1}/><strong>{money(priceOf(builds[i]))}</strong><small>ESTIMATED TOWER PRICE</small></div>)}</div><div className="comparison-table" role="table" aria-label="PC build comparison"><div className="comparison-row comparison-labels" role="row"><span role="columnheader">COMPONENT</span><span role="columnheader">BUILD A</span><span role="columnheader">BUILD B</span></div>{['cpu','gpu','ram','storage','motherboard','psu','case'].map(key=><div className="comparison-row" role="row" key={key}><strong role="rowheader">{key.toUpperCase()}</strong>{parts.map((p,i)=><span role="cell" key={i}>{p[key].name}</span>)}</div>)}{['Gaming','AI / ML','Development','Creative'].map(key=><div className="comparison-row score-compare" role="row" key={key}><strong role="rowheader">{key.toUpperCase()}<small>MODEL SCORE</small></strong>{scores.map((s,i)=><span role="cell" className={valid[i]&&valid[1-i]&&s.scores[key]>scores[1-i].scores[key]?'higher':''} key={i}>{valid[i]?s.scores[key]:'—'}<small>{valid[i]?'/100':'CHECK PARTS'}</small></span>)}</div>)}</div><Note>Higher scores are highlighted per workload. These are relative AFX model scores, not laboratory benchmarks. Prices are illustrative estimates.</Note></section>;}
