import {motion,useReducedMotion} from 'framer-motion';
import {ArrowDown,ArrowUpRight,AudioLines} from 'lucide-react';
import {useApp} from '../hooks/useApp';
import ArfanAssistant,{AssistantBubble} from '../components/ArfanAssistant';
import PCIllustration from '../components/PCIllustration';
import {Action,Reveal} from '../components/Primitives';
import '../styles-laptops.css';
const tools=[['01','BUILD','/builder','Your budget. Your next PC.'],['02','ANALYZE','/analyzer','Meet the hardware you have.'],['03','DESIGNS','/designs','Find your kind of machine.'],['04','UPGRADE','/upgrade','More from what you own.'],['05','COMPARE','/compare','Two builds. A clearer choice.'],['06','PERFORMANCE','/performance','What could your games run at?']];
export default function Home(){const{go}=useApp();return <>
<section className="home-hero"><div className="hero-copy"><div className="eyebrow"><span className="mini-dot"/>PC INTELLIGENCE. WITH PERSONALITY.</div><h1><span>HI.</span><span>THIS IS</span><span className="orange-text">ARFAN<span className="black-text">.</span></span></h1><p>Your PC has potential.<br/>Let’s figure it out, together.</p><div className="hero-actions"><Action to="/builder" data-cursor="BUILD">Let’s build a PC</Action><button className="text-action" onClick={()=>go('/analyzer')} data-cursor="ANALYZE">Analyze my PC <ArrowUpRight size={19}/></button></div></div><div className="hero-character"><div className="hero-model"><PCIllustration accent="#ff3038" variant={1}/></div><ArfanAssistant/><AssistantBubble/></div><div className="hero-foot"><a href="#explore" onClick={event=>{event.preventDefault();document.getElementById('explore')?.scrollIntoView({behavior:'smooth'});}}>SCROLL TO EXPLORE <ArrowDown size={15}/></a><span>CREATED BY SHAIK ARFAN</span><span>01 / MEET YOUR ASSISTANT</span></div></section>
<button className="home-laptop-link" onClick={()=>go('/shop')}><span>YOUR ENTIRE SETUP. ONE SEARCH.<small>Laptops, PC parts and accessories. Photos, prices and Amazon / Flipkart links.</small></span><ArrowUpRight size={34}/></button>
<section id="explore" className="explore-section"><Reveal><span className="eyebrow">GOOD QUESTIONS. BETTER BUILDS.</span><h2>WHAT ARE<br/><span className="outline-text">WE BUILDING?</span></h2></Reveal><div className="explore-orbit"><div className="orbit-middle"><ArfanAssistant small/><span>YOUR NEXT MOVE?</span></div>{tools.map(([n,label,path,desc],i)=><button key={path} className={`orbit-tool orbit-tool-${i}`} onClick={()=>go(path)} data-cursor={label.slice(0,7)}><span>{n}</span><strong>{label}</strong><small>{desc}</small><ArrowUpRight size={24}/></button>)}</div><div className="explore-bottom"><button onClick={()=>go('/compatibility')}>Does it all fit? <b>Check compatibility ↗</b></button><button onClick={()=>go('/browser')}>Curious about this device? <b>See what your browser knows ↗</b></button></div></section></>}
