import {useId,useState,useRef,useEffect} from 'react';
import {motion,useReducedMotion} from 'framer-motion';
import {ArrowUpRight,ArrowRight,ChevronDown,Check} from 'lucide-react';
import {useApp} from '../hooks/useApp';
export function Action({children,onClick,to,secondary=false,className='',...props}){const {go}=useApp();return <button className={`action ${secondary?'secondary':''} ${className}`} onClick={to?()=>go(to):onClick} {...props}>{children}<ArrowUpRight size={20}/></button>;}
export function Reveal({children,className='',delay=0}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.1}} transition={{duration:.65,delay,ease:[.2,.7,.2,1]}}>{children}</motion.div>;}
export function Heading({eyebrow,children,description}){return <div className="section-heading"><span className="eyebrow"><span className="asterisk">✳</span>{eyebrow}</span><Reveal><h1 tabIndex={-1}>{children}</h1></Reveal>{description&&<p className="section-description">{description}</p>}</div>;}
export function Note({children}){return <p className="note">{children}</p>;}
export function SearchSelect({label,options,value,onChange}){
 const id=useId(),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[active,setActive]=useState(0);const wrap=useRef();
 const selected=options.find(o=>o.id===value),shown=options.filter(o=>o.name.toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{const close=e=>{if(!wrap.current?.contains(e.target))setOpen(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
 const choose=o=>{onChange(o.id);setOpen(false);setQuery('');};
 return <div ref={wrap} className={`search-select ${open?'is-open':''}`}><label htmlFor={id}>{label}</label><div className="select-input"><input id={id} role="combobox" aria-expanded={open} aria-controls={`${id}-list`} aria-autocomplete="list" aria-activedescendant={open&&shown.length?`${id}-${active}`:undefined} value={open?query:selected?.name||''} onFocus={()=>{setQuery('');setOpen(true);setActive(0);}} placeholder={selected?.name||'Search components…'} onChange={e=>{setQuery(e.target.value);setActive(0);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);e.stopPropagation();}else if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(a=>Math.min(a+1,shown.length-1));}else if(e.key==='ArrowUp'){e.preventDefault();setActive(a=>Math.max(0,a-1));}else if(e.key==='Enter'&&open){e.preventDefault();if(shown[active])choose(shown[active]);}else if(e.key==='Tab')setOpen(false);}}/><ChevronDown size={17} aria-hidden="true"/></div>{open&&<ul role="listbox" id={`${id}-list`} className="select-options">{shown.length?shown.map((o,i)=><li role="option" aria-selected={o.id===value} id={`${id}-${i}`} key={o.id} onPointerDown={e=>e.preventDefault()} onClick={()=>choose(o)} onMouseEnter={()=>setActive(i)} className={i===active?'active':''}>{o.name}{o.id===value&&<Check size={15}/>}</li>):<li className="no-option">No match in this catalogue.</li>}</ul>}</div>;
}
export function NativeSelect({label,value,onChange,options}){const id=useId();return <div className="native-select"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select></div>;}
export function NextLink({to,children}){const{go}=useApp();return <button className="next-link" onClick={()=>go(to)}>{children}<ArrowRight size={28}/></button>;}
